[app_nodes]
# app-node ansible_host=<APP_NODE_PUBLIC_IP>

[db_nodes]
# db-node ansible_host=<DB_NODE_PRIVATE_IP>

[target_nodes]
# target-node-1 ansible_host=<TARGET_NODE_1_PRIVATE_IP>
# target-node-2 ansible_host=<TARGET_NODE_2_PRIVATE_IP>

[all:vars]
ansible_python_interpreter=/usr/bin/python3
